name: Build Firmware

on:
  push:
    branches:
      - 'main'
      - '!release'
  pull_request:
    branches:
      - '*'
      - '!release*'
  workflow_dispatch:
    branches:
      - '*'
      - '!release*'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
